### PR TITLE
Add support for video captions

### LINKED ISSUE #150: Closed captioning for speeches

### PR DESCRIPTION
**Pull request by taymonbeal**
Fixes: #150

### CODE REVIEW

**Comment by dspeyer** [comment]
This is how this looks on my screen.

Ray has video stretching down to overlap the avatars, which actually looks
ok (at least for this video).  But it means putting closed captions at the
bottom of the video doesn't work.

**Comment by taymonbeal** [comment]
Was there supposed to be a screenshot here? I can't see it.

We can't quite do full-blown CSS-style positioning on the captions, but we do have some options. In particular, we can make the cues appear a fixed number of line-heights from the top or bottom of the video. We can also change this dynamically with JS.

Knowing that, where would be a good place to put the captions?

**Comment by Raemon** [comment]
I think it's probably better to put them towards the top of the video.

**Comment by dspeyer** [comment]
I sent the screenshot on the email, but github stripped it.  You can see it
at http://cpe-74-64-104-129.nyc.res.rr.com/ccss.png

At the top... probably works.  It could overlap a slide title, but it
practice it looks like it won't and I don't think that will vary by
user's screen or similar.

**Comment by taymonbeal** [comment]
My first attempt was in fact obscured by the slide title. I could shift it lower, but then it's starting to cover Ray's face.

Do we actually need slide titles on video slides? Is that useful? I think it would look better if we ditched the slide title.

**Comment by Raemon** [comment]
BTW, I hadn't decided whether to have titles in the video-speech-slides,
and I think now that I know we're doing captions I can just not have slide
titles, or fade them out very quickly as part of the video.

**Comment by taymonbeal** [comment]
FYI, currently captions are off by default, though of course this is straightforward to change.

**Comment by Raemon** [comment]
Yeah off by default is better

**Comment by taymonbeal** [comment]
Quick update: I have now watched this video all the way through with captions and not found any remaining transcription errors.

**Pull request merged**
