### PR TITLE
twilio styling

### PR DESCRIPTION
**Pull request by Raemon**
Changes Twilio to be rectangles, styled vaguely after the images on secularsolstice.com. Uses flexbox to make them wrap reasonably sensibly. Uses max-height to allow up to two rows of them (this probably _also_ wants to be handled in the Twilio backend but seemed good to have a css-failsafe)

After experimenting with the circle-versions, i felt like they needed to be square because I kept being sad that large chunks of me were cropped off and I had to work extra hard to keep my face centered, or resign myself to not really being captured by the camera.

image

### CODE REVIEW

**Comment by taymonbeal** [comment]
What do you mean by "this probably also wants to be handled in the Twilio backend"? Do you mean that it might only be possible to display fewer than 26 people?

If so, would we want this to somehow affect room assignment, or would the idea instead be that if there's not enough room on your screen, you can't see everyone in your room, but they can all still see you?

If the latter, then we don't need any backend support. We should, however, inform the Twilio JS SDK that some people aren't visible, so that it knows not to download video for those people. We can use IntersectionObserver to do this.

**Comment by Raemon** [comment]
Partly this was just referring to the "26 people is the cap" (26 people is how many fit in two rows on my own laptop). But, some people will see even fewer people because their screen is smaller (we can't control for that. I don't think there's a way we can assign rooms that accounts for all the permutations of people with different screen sizes).

Having thought a little more, I think this isn't worth worrying about (yes, it means some people be able to be heard but not seen, which is wasting some bandwidth. I'm not sure what to do about it. Ideally it just means that the video isn't actually downloaded by people who's screen is too small to see it. But, I don't know if there's an easy way to do that without relying on room assignment, and I don't think it's tractable to fix this with room assignment, especially since people can resize their screen willy-nilly)

**Comment by taymonbeal** [comment]
This can be done on the frontend without room assignment by using IntersectionObserver to detect when particular videos are invisible, and using the Twilio JS API (no backend integration needed) to stop downloading video from people who can't be seen (while still being in the same room as them).

**Comment by Raemon** [comment]
Daniel can we merge this in before more merge conflicts accumulate?

**Comment by Raemon** [comment]
(I've merged this into the devel branch now. Still probably good to merge into master)

**Pull request merged**
