### PR TITLE
Lyric & caption fixes

### PR DESCRIPTION
**Pull request by lexandeg**

### CODE REVIEW

**Comment by dspeyer** [comment]
Have you done test runs on the added lines to make sure the timings line up?

Have you checked that the new, longer 5000 Years doesn't trigger the uwsgi headers bug?

**Comment by lexandeg** [comment]
Test ran with the first two commits, noticed a few remaining things leading to the third commit which I will test run shortly. I didn't notice anything wrong on 5000 Years, I asked Taymon what the uwsgi headers bug is and they said to ask you.

**Comment by dspeyer** [comment]
You need to test 5000 Years on the production server, with the exact configuration you'll be using in prod.  This is because we're not 100% sure which piece of infrastructure (we think it's uwsgi, but maybe it's nginx) chokes on headers longer than 4kb.  All lyric timings will end up in a single header at least some of the time.  We don't know exactly how many lines of lyrics is too many, but 5000 Years was pushing it before.  Note that when we discovered this, it was in a song I'd already tested on my dev machine -- using prod infrastructure is key.

**Comment by lexandeg** [comment]
Yes, we did the test run on the secularsolstice2020.org server.

**Pull request merged**
